import Head from "next/head";
import Image from "next/image";
import footerSprite from "@/images/footerSprite.png";
import { NextPageWithLayout } from "./_app";
import AppLayout from "@/layouts/AppLayout";
import { ReactElement } from "react";
import Search from "@/layouts/search";

const KeySVG = () => (
  <svg
    width="19"
    height="18"
    viewBox="0 0 19 18"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M8.38732 8.87103L14.2741 2.98428L15.3346 4.04478L14.2741 5.10603L16.1296 6.96153L15.0691 8.02278L13.2128 6.16653L12.1523 7.22703L13.7431 8.81778L12.6826 9.87903L11.0918 8.28753L9.44782 9.93153C9.95816 10.707 10.1628 11.6442 10.0223 12.5619C9.88168 13.4795 9.40585 14.3125 8.68677 14.8996C7.96768 15.4868 7.05643 15.7865 6.1292 15.7408C5.20197 15.695 4.32463 15.3071 3.66682 14.652C3.00759 13.9953 2.61609 13.1169 2.56841 12.1876C2.52073 11.2582 2.82027 10.3444 3.40882 9.6236C3.99738 8.90282 4.83289 8.42661 5.75299 8.28753C6.67308 8.14845 7.61202 8.35642 8.38732 8.87103ZM7.90957 13.5908C8.12805 13.3841 8.30289 13.1358 8.42375 12.8604C8.54461 12.585 8.60903 12.2882 8.61322 11.9875C8.6174 11.6867 8.56125 11.3882 8.4481 11.1096C8.33494 10.831 8.16708 10.5778 7.95442 10.3652C7.74177 10.1525 7.48864 9.98465 7.21 9.8715C6.93135 9.75835 6.63286 9.7022 6.33215 9.70638C6.03143 9.71057 5.73461 9.77499 5.45923 9.89585C5.18384 10.0167 4.93548 10.1915 4.72882 10.41C4.31896 10.8344 4.09217 11.4027 4.0973 11.9927C4.10243 12.5826 4.33906 13.147 4.75622 13.5641C5.17339 13.9813 5.73772 14.2179 6.32766 14.223C6.91761 14.2282 7.48596 14.0014 7.91032 13.5915L7.90957 13.5908Z"
      fill="#818182"
    />
  </svg>
);

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Artizen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-12">
        <section>
          <div className="flex justify-center">
            <KeySVG />
            <h3 className="uppercase ml-1.5 hero-text-1 font-bold">
              Now in Private Beta
            </h3>
          </div>
          <h3 className="font-bold hero-text-2 max-w-[882.78px] text-center lg:text-[54px] xl:text-[64.54px] leading-[60.24px] lg:h-[160px] mt-[30px] mx-auto">
            {"From inspiration to execution, we’ve got you covered."}
          </h3>
          <p className="text-white max-w-[504px] text-center text-xl mx-auto">
            {
              "Collaborate, share, and monetize your work. With everything you need in one place, it’s time to create your best work "
            }
            <span className="font-bold hero-sub-text-gradient">yet.</span>
          </p>
        </section>
        <Search />
        <section className="flex items-center text-[#606060] justify-between">
          <ul className="flex items-center justify-center flex-1 font-bold uppercase">
            <li className="pr-2">Twitter</li>
            <li className="pl-2 border-l border-[#606060]">Linkedin</li>
          </ul>
          <div className="relative flex-1 h-[443px] w-[567px]">
            <Image src={footerSprite.src} fill alt="footer image" />
          </div>
          <ul className="flex items-center justify-center flex-1 font-bold uppercase">
            <li>privacy policy</li>
          </ul>
        </section>
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <AppLayout>{page}</AppLayout>;

export default Home;
